image: ruby:2.3

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - bundle install

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public --baseurl /thinktheweb.com/
  artifacts:
    paths:
    - public
  only:
  - staging

deploy:
  stage: deploy
  script:
  - echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" >> /etc/apt/sources.list.d/java-8-debian.list
  - echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" >> /etc/apt/sources.list.d/java-8-debian.list
  - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886
  - apt-get update
  - echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | debconf-set-selections
  - apt-get install -y oracle-java8-installer
  - apt-get install -y oracle-java8-set-default
  - bundle exec jekyll build -d public
  - bundle exec s3_website push --site=public
  only:
  - master
